kind: pipeline
type: docker
name: smart-iot

steps:
  - name: 编译打包代码
    image: maven:3-jdk-10
    volumes:
      - name : mvncache
        path : /root/.m2
    commands:
      - echo 'test echo'
      - cd  ./service
      - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B

  # - name: 构建镜像&PUSH镜像到Hub.
  #   image: plugins/docker
  #   settings:
  #     dockerfile: ./Dockerfile
  #     use_cache: true
  #     repo: registry.cn-hangzhou.aliyuncs.com/windwithlife/smart-iot
  #     registry: registry.cn-hangzhou.aliyuncs.com
  #     mirror: https://89cgb0wn.mirror.aliyuncs.com
  #     username: 379163259@qq.com
  #     password: password7&
  #     # 更多变量参考https://docs.drone.io/pipeline/environment/reference/
  #     tags:
  #       - ${DRONE_TAG=latest}
  #       - build-${DRONE_BUILD_NUMBER}



  - name: 部署到集群-dron8s方式
    image: bh90210/dron8s:latest
    settings:
      yaml: ./deployment.yaml
      kubeconfig:
        from_secret: kubeconfig
      # variables. Must be lowercase, Usage: {{.service_name}}
      service_name: service-iot
      app_name: smart-iot
      repo_name: smart-iot
      build_tag: build-90
      # build_tag: build-${DRONE_BUILD_NUMBER}

volumes:
  - name: mvncache
    host:
      path: /var/lib/cache/.m2

trigger:
  branch:
    - master
  event:
    - push
