kind: pipeline
type: docker
name: smart-iot

steps:
  - name: 编译打包代码
    image: maven:3-jdk-10
    volumes:
      - name : mvncache
        path : /root/.m2
    commands:
      - echo 'test echo'
      - cd  ./service
      - mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B

  - name: 构建镜像&PUSH镜像到Hub.
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      use_cache: true
      repo: ccr.ccs.tencentyun.com/windwithlife/smart-iot
      registry: ccr.ccs.tencentyun.com
      mirror: https://89cgb0wn.mirror.aliyuncs.com
      username: 100008098144
      password: password7&
      # 更多变量参考https://docs.drone.io/pipeline/environment/reference/
      tags:
        - ${DRONE_TAG=latest}
        - build-${DRONE_BUILD_NUMBER}



  - name: 部署到集群-dron8s方式
    image: bh90210/dron8s:latest
    settings:
      yaml: ./deployment.yaml
      kubeconfig:
        from_secret: kubeconfig-iot
      image_name: ccr.ccs.tencentyun.com/windwithlife/smart-iot
      service_name: service-iot
      app_name: smart-iot
      build_tag: build-${DRONE_BUILD_NUMBER}

volumes:
  - name: mvncache
    host:
      path: /var/lib/cache/.m2

trigger:
  branch:
    - smart-iot
  event:
    - push
