kind: pipeline
type: docker
name: smart-iot

steps:
  - name: build
    image: maven:3-jdk-10
    volumes:
      - name : mvncache
        path : /root/.m2
    commands:
      - echo 'test echo'
      - cd  ./service
      - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


  - name: k8s-deploy
    # Kubernetes插件
    image: danielgormly/drone-plugin-kube:0.2.0
    settings:
      build_tag: build-${DRONE_BUILD_NUMBER}
      template: ./deployment.yaml
      server: https://drone.koudaibook.com:6443
      token: 2sq4np.438e1zlp5o9mf56g
      ca: 265b9d9b0a5668f430cefe6f6896d19f593e553656d581143e0de188b3f31638

volumes:
  - name: mvncache
    host:
      path: /var/lib/cache/.m2

trigger:
  branch:
    - master
  event:
    - push
