kind: pipeline
type: docker
name: smart-iot

steps:
#  - name: build
#    image: maven:3-jdk-10
#    volumes:
#      - name : mvncache
#        path : /root/.m2
#    commands:
#      - echo 'test echo'
#      - cd  ./service
#      - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

  #- name: 编译&构建镜像
  #  image: plugins/docker
    # 挂载主机的docker

#    settings:
#      dockerfile: ./Dockerfile
#      repo: registry.cn-hangzhou.aliyuncs.com/windwithlife/smart-iot
#      registry: registry.cn-hangzhou.aliyuncs.com
#      mirror: https://89cgb0wn.mirror.aliyuncs.com
#      username: 379163259@qq.com
#      password: password7&
#      # 更多变量参考https://docs.drone.io/pipeline/environment/reference/
#      tags:
#        - ${DRONE_TAG=latest}
#        - build-${DRONE_BUILD_NUMBER}

#  - name: k8s-deploy
#    # Kubernetes插件
#    image: danielgormly/drone-plugin-kube:0.2.0
#    settings:
#      build_tag: build-${DRONE_BUILD_NUMBER}
#      template: ./deployment.yaml
#      server: https://drone.koudaibook.com:6443
#      token: 2sq4np.438e1zlp5o9mf56g
#      ca: 265b9d9b0a5668f430cefe6f6896d19f593e553656d581143e0de188b3f31638

  - name: 部署到集群-dron8s方式
    image: bh90210/dron8s:latest
    settings:
      yaml: ./deployment.yaml
      kubeconfig:
        from_secret: kubeconfig
      # variables. Must be lowercase, Usage: {{.service_name}}
      service_name: iot-service
      image_version: 1.8
      build_tag: build-${DRONE_BUILD_NUMBER}

volumes:
  - name: mvncache
    host:
      path: /var/lib/cache/.m2

trigger:
  branch:
    - master
  event:
    - push
