apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-iot
  namespace: default
  labels:
    app: app-iot
    name: app-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-iot
      name: app-iot
  template:
    metadata:
      labels:
        app: app-iot
        name: app-iot
    spec:
      containers:
        - name: container-smart-iot
          image: registry.cn-hangzhou.aliyuncs.com/windwithlife/{{.repo_name}}:{{.build_tag}}
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: {{.service_name}}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: app-iot

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-{{.app_name}}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "token,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/cors-expose-headers: "token"
    nginx.ingress.kubernetes.io/ssl-redirect: 'false' #http
spec:
  ingressClassName: nginx
  tls:
  - secretName: ingress-cert-koudaibook
    hosts:
    - service.koudaibook.com
  rules:
    - host: service.koudaibook.com
      http:
        paths:
          - path: /{{.app_name}}
            pathType: Prefix
            backend:
              serviceName: {{.service_name}}
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-{{.app_name}}-websocket
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false' #http 自动转https
    nginx.ingress.kubernetes.io/configuration-snippet: |
       proxy_set_header Upgrade "websocket";
       proxy_set_header Connection "Upgrade";
       proxy_read_timeout 600s; #配置点2，如果没效，可以考虑这个时间配置长一点
spec:
  ingressClassName: nginx
  tls:
  - secretName: ingress-cert-koudaibook
    hosts:
    - service.koudaibook.com
  rules:
    - host: service.koudaibook.com
      http:
        paths:
          - path: /{{.app_name}}/webSocket
            pathType: Prefix
            backend:
              serviceName: {{.service_name}}
              servicePort: 80