apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-iot
  namespace: default
  labels:
    app: app-iot
    name: app-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-iot
      name: app-iot
  template:
    metadata:
      labels:
        app: app-iot
        name: app-iot
    spec:
      containers:
        - name: container-smart-iot
          image: registry.cn-hangzhou.aliyuncs.com/windwithlife/{{.repo_name}}:{{.build_tag}}
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
