
spring:
  datasource:
    url: jdbc:mysql://47.101.223.234:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1qazxsw2
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: manager.e-healthcare.net
    password: meetinglive
    port: 31379
  mqtt:
    server:
      username: admin
      password: public
      url: tcp://drone.koudaibook.com:1883
    client:
      publishId: "publish-id"
      subscribeId: "subscribe-id"
    default:
      topic: "ci/simple/center/soa-server/#"
      completionTimeout: 3000

server:
  servlet:
    context-path: /smart-iot
simple:
  domainName: koudaibook.com
qiniu:
  accessKey: JMVsA4svqk_TUAjq9jOKy0fLVxBaJpiaAAhcn0gr
  secretKey: 39xrdVIpTa65jjPkAB9RCjzdDKN_VY4KdcPkhNjD
  bucket: windwithlife
  domainName: http://images.koudaibook.com